runtime: php55
api_version: 1

handlers:
  - url: /user_guide
    static_dir: user_guide
  - url: /app/themes
    static_dir: app/themes
  - url: /public
    static_dir: public
  - url: /.*
    script: index.php
