<?php

$config['assets_homepage-bottom_js'] = array(
// 	'public/assets/themes/global/vendor/animsition/animsition.min.js',
// 	'public/assets/themes/global/vendor/asscroll/jquery-asScroll.min.js',
// 	'public/assets/themes/global/vendor/mousewheel/jquery.mousewheel.min.js',
// 	'public/assets/themes/global/vendor/asscrollable/jquery.asScrollable.all.min.js',
// 	'public/assets/themes/global/vendor/ashoverscroll/jquery-asHoverScroll.min.js',
// 	'public/assets/themes/global/vendor/switchery/switchery.min.js',
// 	'public/assets/themes/global/vendor/intro-js/intro.min.js',
// 	'public/assets/themes/global/vendor/screenfull/screenfull.min.js',
// 	'public/assets/themes/global/vendor/slidepanel/jquery-slidePanel.min.js',
// 	'public/assets/themes/global/vendor/raty/jquery.raty.js',
// 	'public/assets/themes/global/vendor/chartist-js/chartist.min.js',
// 	'public/assets/themes/global/vendor/gmaps/gmaps.js',
// 	'public/assets/themes/global/vendor/matchheight/jquery.matchHeight-min.js',
// 	'public/assets/themes/global/vendor/summernote/summernote.min.js',
// 	'public/assets/themes/center/assets/js/site.min.js',
// 	'public/assets/themes/center/assets/js/sections/menu.min.js',
// 	'public/assets/themes/center/assets/js/sections/menubar.min.js',
// 	'public/assets/themes/center/assets/js/sections/sidebar.min.js',
// 	'public/assets/themes/global/js/configs/config-colors.min.js',
// 	'public/assets/themes/center/assets/js/configs/config-tour.min.js',
// 	'public/assets/themes/global/js/components/asscrollable.min.js',
// 	'public/assets/themes/global/js/components/animsition.min.js',
// 	'public/assets/themes/global/js/components/slidepanel.min.js',
// 	'public/assets/themes/global/js/components/switchery.min.js',
// 	'public/assets/themes/global/js/components/summernote.min.js',
// 	'public/assets/themes/global/js/components/gmaps.min.js',
// 	'public/assets/themes/global/js/components/matchheight.min.js',
// 	'public/assets/themes/global/js/components/raty.min.js',
// 'public/assets/themes/global/vendor/p-loading/p-loading.min.js',
	
// 	'public/assets/themes/global/js/components/jt-timepicker.min.js',
// 	'public/assets/themes/global/js/components/datepair-js.min.js',

// 	'public/assets/themes/center/assets/examples/js/dashboard/v2.min.js',
// );
$config['assets_homepage_js'] = array(
    // 'public/assets/themes/center/assets/js/sections/skintools.min.js',
	// 'public/assets/themes/global/vendor/modernizr/modernizr.min.js',
 //    'public/assets/themes/global/vendor/breakpoints/breakpoints.min.js',
 //    'public/assets/themes/global/vendor/jquery/jquery.min.js',
 //    'public/assets/themes/global/vendor/lazy/jquery.lazy.min.js',
 //    'public/assets/themes/global/vendor/lazy/jquery.lazy.plugins.min.js',
 //    'public/assets/themes/global/vendor/bootstrap/bootstrap.min.js',
 //    'public/assets/themes/global/js/core.min.js',
 //    'public/assets/themes/global/js/timeago.min.js',
 //    'public/assets/themes/global/js/timeago.locales.min.js',
 //    'public/assets/themes/global/vendor/toastr/toastr.min.js',
 //    'public/assets/gc/js/jquery_plugins/jquery-migrate-1.1.0.min.js',
 //    'public/assets/themes/global/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js',
 //    'public/assets/themes/global/js/components/bootstrap-datepicker.min.js',
 //    'app/modules/homepage/assets/js/vue.js',
 //    'app/modules/homepage/assets/js/vue-resource.js',
 //    'app/modules/homepage/assets/js/app.js',

 //    'app/modules/homepage/assets/js/Paginate.js',
);
$config['assets_homepage_css'] = array(
    // 'public/assets/themes/global/css/bootstrap.min3f0d.css',
    // 'public/assets/themes/global/css/bootstrap-extend.min3f0d.css',
    // 'public/assets/themes/center/assets/css/site.min3f0d.css',
    // 'public/assets/themes/global/vendor/bootstrap-datepicker/bootstrap-datepicker.min3f0d.css',
    // 'public/assets/themes/global/vendor/jt-timepicker/jquery-timepicker.min3f0d.css',
    // // 'public/assets/themes/global/css/skintools.min3f0d.css',
    // 'public/assets/themes/global/vendor/animsition/animsition.min3f0d.css',
    // 'public/assets/themes/global/vendor/asscrollable/asScrollable.min3f0d.css',
    // 'public/assets/themes/global/vendor/switchery/switchery.min3f0d.css',
    // 'public/assets/themes/global/vendor/intro-js/introjs.min3f0d.css',
    // 'public/assets/themes/global/vendor/slidepanel/slidePanel.min3f0d.css',
    // 'public/assets/themes/global/vendor/flag-icon-css/flag-icon.min3f0d.css',
    // 'public/assets/themes/global/vendor/toastr/toastr.min3f0d.css',
    // 'public/assets/themes/center/assets/examples/css/advanced/toastr.min3f0d.css',
    // 'public/assets/themes/global/vendor/chartist-js/chartist.min3f0d.css',
    // 'public/assets/themes/global/vendor/summernote/summernote.min3f0d.css',
    // 'public/assets/themes/global/vendor/aspieprogress/asPieProgress.min3f0d.css',
    // 'public/assets/themes/center/assets/examples/css/dashboard/v2.min3f0d.css',
    // 'public/assets/themes/global/fonts/web-icons/web-icons.min3f0d.css',
    // 'public/assets/themes/global/fonts/brand-icons/brand-icons.min3f0d.css',
    // 'public/assets/themes/global/fonts/font-awesome/font-awesome.min3f0d.css',
    // 'public/assets/themes/global/vendor/p-loading/p-loading.min.css',
    // 'app/themes/neutral/assets/font.css',
    // 'app/themes/tirto/css/style.css',
    // // 'app/themes/neutral/assets/homepage.css',
);

$config['assets_management-top_js'] = array(
	// 'public/assets/themes/global/vendor/modernizr/modernizr.min.js',
	// 'public/assets/themes/global/vendor/breakpoints/breakpoints.min.js',
	// 'public/assets/themes/global/vendor/jquery/jquery.min.js',
	// 'public/assets/themes/global/vendor/bootstrap/bootstrap.min.js',
	// 'public/assets/themes/global/js/core.min.js',
	// 'public/assets/gc/js/jquery_plugins/jquery-migrate-1.1.0.min.js',
	// 'app/modules/homepage/assets/js/vue.js',
 //    'app/modules/homepage/assets/js/vue-resource.js',
);
$config['assets_management-bottom_js'] = array(
	// 'public/assets/themes/global/vendor/animsition/animsition.min.js',
	// 'public/assets/themes/global/vendor/asscroll/jquery-asScroll.min.js',
	// 'public/assets/themes/global/vendor/mousewheel/jquery.mousewheel.min.js',
	// 'public/assets/themes/global/vendor/asscrollable/jquery.asScrollable.all.min.js',
	// 'public/assets/themes/global/vendor/ashoverscroll/jquery-asHoverScroll.min.js',
	// 'public/assets/themes/global/vendor/switchery/switchery.min.js',
	// 'public/assets/themes/global/vendor/intro-js/intro.min.js',
	// 'public/assets/themes/global/vendor/screenfull/screenfull.min.js',
	// 'public/assets/themes/global/vendor/slidepanel/jquery-slidePanel.min.js',
	// 'public/assets/themes/global/vendor/chartist-js/chartist.min.js',
	// 'public/assets/themes/global/vendor/gmaps/gmaps.js',
	// 'public/assets/themes/global/vendor/matchheight/jquery.matchHeight-min.js',
	// 'public/assets/themes/global/vendor/summernote/summernote.min.js',
	// 'public/assets/themes/global/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js',
	// 'public/assets/themes/global/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js',
	// 'public/assets/themes/global/vendor/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.id.js',
	// 'public/assets/themes/global/vendor/select2/select2.min.js',
	// 'public/assets/themes/global/vendor/bootbox/bootbox.js',
	// 'public/assets/themes/global/vendor/bootstrap-sweetalert/sweet-alert.min.js',
	// 'public/assets/themes/global/vendor/toastr/toastr.min.js',

	// 'public/assets/themes/global/vendor/p-loading/p-loading.min.js',
	// 'public/assets/themes/global/js/components/select2.min.js',
	// 'public/assets/themes/center/assets/js/site.min.js',
	// 'public/assets/themes/center/assets/js/sections/menu.min.js',
	// 'public/assets/themes/center/assets/js/sections/menubar.min.js',
	// 'public/assets/themes/center/assets/js/sections/sidebar.min.js',
	// 'public/assets/themes/global/js/configs/config-colors.min.js',
	// 'public/assets/themes/center/assets/js/configs/config-tour.min.js',
	// 'public/assets/themes/global/js/components/asscrollable.min.js',
	// 'public/assets/themes/global/js/components/animsition.min.js',
	// 'public/assets/themes/global/js/components/slidepanel.min.js',
	// 'public/assets/themes/global/js/components/switchery.min.js',
	// 'public/assets/themes/global/js/components/summernote.min.js',
	// 'public/assets/themes/global/js/components/gmaps.min.js',
	// 'public/assets/themes/global/js/components/matchheight.min.js',
	// 'public/assets/themes/global/js/components/bootstrap-datepicker.min.js',
	// 'public/assets/themes/global/js/components/jt-timepicker.min.js',
	// 'public/assets/themes/global/js/components/datepair-js.min.js',
	// 'public/assets/themes/global/js/components/bootbox.min.js',
	// 'public/assets/themes/global/js/components/bootstrap-sweetalert.min.js',
	// 'public/assets/themes/global/js/components/toastr.min.js',
	// 'public/assets/themes/center/assets/examples/js/dashboard/v2.min.js'
);
$config['assets_management_css'] = array(
// 	'public/assets/themes/global/css/bootstrap.min3f0d.css',
// 	'public/assets/themes/global/css/bootstrap-extend.min3f0d.css',
// 	'public/assets/themes/center/assets/css/site.min3f0d.css',
// 	'public/assets/themes/global/css/skintools.min3f0d.css',
// 	'public/assets/themes/global/vendor/animsition/animsition.min3f0d.css',
// 	'public/assets/themes/global/vendor/asscrollable/asScrollable.min3f0d.css',
// 	'public/assets/themes/global/vendor/switchery/switchery.min3f0d.css',
// 	'public/assets/themes/global/vendor/intro-js/introjs.min3f0d.css',
// 	'public/assets/themes/global/vendor/slidepanel/slidePanel.min3f0d.css',
// 	'public/assets/themes/global/vendor/flag-icon-css/flag-icon.min3f0d.css',
// 	'public/assets/themes/global/vendor/chartist-js/chartist.min3f0d.css',
// 	'public/assets/themes/global/vendor/summernote/summernote.min3f0d.css',
// 	'public/assets/themes/global/vendor/aspieprogress/asPieProgress.min3f0d.css',
// 	'public/assets/themes/center/assets/examples/css/dashboard/v2.min3f0d.css',
// 	'public/assets/themes/global/fonts/web-icons/web-icons.min3f0d.css',
// 	'public/assets/themes/global/fonts/brand-icons/brand-icons.min3f0d.css',
// 	'public/assets/themes/global/fonts/font-awesome/font-awesome.min3f0d.css' ,
// 	'public/assets/themes/global/vendor/bootstrap-datepicker/bootstrap-datepicker.min3f0d.css',
// 	'public/assets/themes/global/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css',
//     'public/assets/themes/global/vendor/jt-timepicker/jquery-timepicker',
//     'public/assets/themes/global/vendor/alertify-js/alertify.min3f0d.css',
//     'public/assets/themes/global/vendor/select2/select2.min3f0d.css',
//     'public/assets/themes/global/vendor/bootstrap-sweetalert/sweet-alert.min3f0d.css',
//     'public/assets/themes/global/vendor/toastr/toastr.min3f0d.css',
//     'public/assets/themes/global/vendor/p-loading/p-loading.css'
// );

$config['assets_gc_template_css'] = array(
	// 'public/assets/themes/global/vendor/datatables-bootstrap/dataTables.bootstrap.min3f0d.css',
	// 'public/assets/themes/global/vendor/datatables-fixedheader/dataTables.fixedHeader.min3f0d.css',
	// 'public/assets/themes/global/vendor/datatables-responsive/dataTables.responsive.min3f0d.css',
	// 'public/assets/themes/center/assets/examples/css/tables/datatable.min3f0d.css',
);
$config['assets_gc_template_js'] = array(
	// 'public/assets/themes/global/js/components/datatables.min.js',
	// 'public/assets/themes/global/vendor/datatables/jquery.dataTables.min.js',
	// 'public/assets/themes/global/vendor/datatables-fixedheader/dataTables.fixedHeader.js',
	// 'public/assets/themes/global/vendor/datatables-bootstrap/dataTables.bootstrap.min.js',
	// 'public/assets/themes/global/vendor/datatables-responsive/dataTables.responsive.js',
	// 'public/assets/themes/global/vendor/datatables-tabletools/dataTables.tableTools.js',
	// 'public/assets/themes/global/vendor/asrange/jquery-asRange.min.js',
	// 'public/assets/themes/global/vendor/alertify-js/alertify.js',
	// 'public/assets/themes/global/js/components/alertify-js.min.js',
	// 'public/assets/themes/global/vendor/bootbox/bootbox.js',
);