dashboard:
    credentials: ['superadmin','admin']
    title: Dashboard
    icon: icon-home
    items:
        dashboard/statistik: Statistik
transaksi:
    credentials: ['superadmin','admin']
    title: Transaction
    icon: icon-globe
    items:
        transaksi/fasilitas: 'Facilities'
        transaksi/tenan: 'Tenant'
        transaksi/redeem-poin: 'Redeem Points'
        transaksi/histori-transaksi-poin: 'History Points'
        # transaksi/pengaturan: 'Pengaturan'
        # transaksi/pengaturan-nilai-poin: 'Pengaturan Nilai Poin'
        # transaksi/histori-check-inout: Histori Cek In/Out
        # transaksi/histori-redeem-poin: Histori Redeem Poin
manajemen:
    credentials: ['superadmin','admin']
    title: Management
    icon: icon-puzzle
    items:
        manajemen/member: 'Member'
        manajemen/cluster: Cluster
        manajemen/unit: Units
        manajemen/tenan: Tenant
        manajemen/fasilitas: Facilities
        manajemen/marcendaise: Merchandise
        manajemen/unit-poin: 'Unit Points'
laporan:
    credentials: ['superadmin','admin']
    title: Reporting
    icon: icon-bar-chart
    items:
        laporan/unit-poin-member-details: 'Member & Points'
        # laporan/poin-unit: 'Poin Unit'
        laporan/tenan-fasilitas: 'Club House Facilities'
        laporan/transaksi-unit-poin: 'Club House Tenant'
        # laporan/transaksi-check-inout: Marcendaise
        # laporan/transaksi-redeempoin: 'Redeem Poin'
        
pengaturan:
    credentials: ['superadmin']
    title: Pengaturan
    icon: icon-wrench
    items:
        pengaturan/grup: Grup
        pengaturan/pengguna: Pengguna
        pengaturan/setting: Setting
        pengaturan/modul: Modul
        pengaturan/otoritas: Otoritas
        pengaturan/navigation: 'Akses Route'
        pengaturan/hak_akses: 'Hak Akses'
