artisan:
    module_id: '1'
    module_name: artisan
    module_path: artisan
    version: '1.0'
    user_id: '1'
account:
    module_id: '4'
    module_name: account
    module_path: account
    version: '1.0'
    user_id: '4'
dashboard:
    module_id: '5'
    module_name: dashboard
    module_path: dashboard
    version: '1.0'
    user_id: '1'
navigation:
    module_id: '6'
    module_name: navigation
    module_path: navigation
    version: '1.0'
    user_id: '1'
transaksi:
    module_id: '18'
    module_name: transaksi
    module_path: transaksi
    version: '1.0'
    user_id: '1'
pengaturan:
    module_id: '19'
    module_name: pengaturan
    module_path: pengaturan
    version: '1.0'
    user_id: '1'
manajemen:
    module_id: '20'
    module_name: manajemen
    module_path: manajemen
    version: '1.0'
    user_id: '1'
laporan:
    module_id: '22'
    module_name: laporan
    module_path: laporan
    version: '1.0'
    user_id: '1'
