artisan:
    module_id: '1'
    module_name: artisan
    module_path: artisan
    version: '1.0'
    user_id: '1'
main:
    module_id: '2'
    module_name: main
    module_path: main
    version: '1.0'
    user_id: '1'
lavon:
    module_id: '3'
    module_name: lavon
    module_path: lavon
    version: '1.0'
    user_id: '1'
account:
    module_id: '4'
    module_name: account
    module_path: account
    version: '1.0'
    user_id: '2'
