dashboard:
    credentials: ['superadmin','admin']
    title: Dashboard
    icon: icon-home
    items:
        dashboard/statistik: Statistik
transaksi:
    credentials: ['superadmin','admin']
    title: Transaksi
    icon: icon-globe
    items:
        transaksi/fasilitas: 'Fasilitas'
        transaksi/tenan: 'Tenan'
        transaksi/redeem-poin: 'Redeem Poin'
        transaksi/histori-transaksi-poin: 'Histori Transaksi Poin'
        # transaksi/pengaturan: 'Pengaturan'
        # transaksi/pengaturan-nilai-poin: 'Pengaturan Nilai Poin'
        # transaksi/histori-check-inout: Histori Cek In/Out
        # transaksi/histori-redeem-poin: Histori Redeem Poin
manajemen:
    credentials: ['superadmin','admin']
    title: Manajemen
    icon: icon-puzzle
    items:
        manajemen/cluster: Cluster
        manajemen/member: 'Member'
        manajemen/unit: Unit
        manajemen/tenan: Tenan
        manajemen/fasilitas: Fasilitas
        manajemen/marcendaise: Marcendaise
        # manajemen/unit-poin: 'Unit Poin'
laporan:
    credentials: ['superadmin','admin']
    title: Laporan
    icon: icon-bar-chart
    items:
        laporan/unit-poin-member-details: 'Unit, Poin & Member Details'
        # laporan/poin-unit: 'Poin Unit'
        laporan/tenan-fasilitas: 'Tenan & Fasilitas'
        laporan/transaksi-unit-poin: 'Transaksi Unit & Poin'
        # laporan/transaksi-check-inout: Marcendaise
        # laporan/transaksi-redeempoin: 'Redeem Poin'
        
pengaturan:
    credentials: ['superadmin']
    title: Pengaturan
    icon: icon-wrench
    items:
        pengaturan/grup: Grup
        pengaturan/pengguna: Pengguna
        pengaturan/setting: Setting
        pengaturan/modul: Modul
        pengaturan/otoritas: Otoritas
        pengaturan/navigation: 'Akses Route'
        pengaturan/hak_akses: 'Hak Akses'
