artisan:
    module_id: '1'
    module_name: artisan
    module_path: artisan
    version: '1.0'
    user_id: '1'
main:
    module_id: '2'
    module_name: main
    module_path: main
    version: '1.0'
    user_id: '1'
apps:
    module_id: '3'
    module_name: apps
    module_path: apps
    version: '1.0'
    user_id: '1'
account:
    module_id: '4'
    module_name: account
    module_path: account
    version: '1.0'
    user_id: '4'
dashboard:
    module_id: '5'
    module_name: dashboard
    module_path: dashboard
    version: '1.0'
    user_id: '1'
navigation:
    module_id: '6'
    module_name: navigation
    module_path: navigation
    version: '1.0'
    user_id: '1'
unit:
    module_id: '7'
    module_name: unit
    module_path: unit
    version: '1.0'
    user_id: '1'
cluster:
    module_id: '8'
    module_name: cluster
    module_path: cluster
    version: '1.0'
    user_id: '1'
tenan:
    module_id: '9'
    module_name: tenan
    module_path: tenan
    version: '1.0'
    user_id: '1'
member:
    module_id: '10'
    module_name: member
    module_path: member
    version: '1.0'
    user_id: '1'
